name: 'webfactory/create-aws-codedeploy-deployment'
description: 'An Action to deploy GitHub repos with AWS CodeDeploy'
inputs:
    application:
        description: 'AWS CodeDeploy application name; defaults to short repository name'
    skip-sequence-check:
        description: 'When set, skip the check making sure no earlier workflow results are deployed'
        default: false
    config-name:
        description: 'Override name to look up branch_config; default is to use the current branch name.'
        default: ''
outputs:
    deploymentId:
        description: AWS CodeDeployment Deployment-ID of the deployment created
    deploymentGroupName:
        description: AWS CodeDeployment Deployment Group name used
    deploymentGroupCreated:
        description: True, if a new deployment group was created; false if an already existing group was used.
runs:
    using: 'node12'
    main: 'dist/index.js'

branding:
    icon: cast
    color: orange
